homeassistant:
  # Name of the location where Home Assistant is running
  name: !secret ha_name
  # Location required to calculate the time the sun rises and sets
  latitude: !secret ha_lat
  longitude: !secret ha_lon
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret ha_elv
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Oslo
  # Customization file
  customize: !include customize.yaml
#  packages: !include_dir_named packages
  whitelist_external_dirs:
    - /opt

# Show links to resources in log and frontend
# introduction:

# Enables the frontend
frontend:

# Enable mobile app
mobile_app:

# Enables configuration UI
config:

# Enable system health
system_health:

http:
  # Secrets are defined in the file secrets.yaml
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:
  ignore:
    - apple_tv

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Enable configurator web view
panel_iframe:
  configurator:
    title: Konfigurasjon
    icon: mdi:wrench
    url: http://192.168.1.7:3218

# Enable logging to influx database home_assistant (created manually)
influxdb:
  host: 127.0.0.1
  port: 8086
  database: home_assistant
  default_measurement: state
  include:
    entities:
      - sensor.electricity_price_pers_vei_12
      - sensor.real_time_consumption_pers_vei_12
      - sensor.netatmo_outdoor_temperature
      - sensor.p12_varsel_temperature
      - sensor.stue_temperature
      - sensor.speedtest_upload
      - sensor.speedtest_download
      - sensor.speedtest_ping
      - sensor.pi_hole_ads_blocked_today
      - sensor.pi_hole_ads_percentage_blocked_today
      - sensor.pi_hole_dns_queries_cached
      - sensor.pi_hole_dns_queries_forwarded
      - sensor.pi_hole_dns_queries_today
      - sensor.pi_hole_dns_unique_clients
      - sensor.pi_hole_domains_blocked
      - sensor.pi_hole_seen_clients
      - sensor.speilrom_temperature
      - sensor.kjokken_temperature
      - sensor.soverom_barn_temperature
      - sensor.soveromsgang_temperature
      - sensor.gang_underetasje_temperature
  exclude:
    domains:
      - group

# Enable database purge at a schedule
recorder:
  purge_keep_days: 10
  exclude:
    domains:
      - automation
      - weblink
      - updater
    entities:
      - sun.sun
      - sensor.last_boot
      - sensor.date

# Customization of P12  

# Z-wave
zwave:
  usb_path: /dev/ttyACM0
  
# Enabling logging of components of interest
logger:
  default: critical
  logs:
    homeassistant.components.nissan_leaf: debug
    homeassistant.components.sensor.nissan_leaf: debug
    homeassistant.components.switch.nissan_leaf: debug

# MQTT
mqtt:
#  password: !secret mqtt_password
#  broker: 192.168.1.7

# Speedtest.net
speedtestdotnet:

#Xiaomi Roborock vacuum robot
#vacuum:
#  - platform: xiaomi_miio
#    host: 
#    token: 

  
# Verisure
verisure:
  username: !secret verisure_user
  password: !secret verisure_password

#Octoprint
octoprint:
  host: 192.168.1.154
  api_key: 9818A2BCB3A34EE2B494A577244B88A1

# IFTTT
ifttt:
  key: !secret ifttt_apikey

# iOS
ios:

# Tibber
tibber:
  access_token: !secret tibber_token

# Unifi camera
# Note: API key found at Unifi video admin page under Users/
# in your admin profile where API ACCESS lies.
camera:
  - platform: uvc
    nvr: 192.168.1.9
    key: !secret uvc_key
    port: 7080
    password: !secret uvc_password
    
  - platform: generic
    name: Vær
    still_image_url: https://www.yr.no/sted/Norge/Hordaland/Bergen/Bergen/meteogram.svg
    content_type: 'image/svg+xml'

# Netatmo
# Note: API- and secret-key ID found at developer API page for 
# Netatmo (login required)
netatmo:
  api_key: !secret netatmo_apikey
  secret_key: !secret netatmo_secretkey
  username: !secret netatmo_user
  password: !secret netatmo_password

# NIBE heatpump
nibe:
  systems:
    - system: 26191
      units:
        - unit: 0
          categories: True
          statuses: True
      climates: True
      water_heaters: True
      fans: True

# Nissan Leaf
nissan_leaf:
  username: !secret nissanleaf_user
  password: !secret nissanleaf_password
  region: !secret nissanleaf_region
  update_interval:
    hours: 1
  update_interval_charging:
    minutes: 15
  update_interval_climate:
    minutes: 5

# Tesla
tesla:
    username: !secret tesla_user
    password: !secret tesla_password

# Neato
neato:
  username: !secret neato_user
  password: !secret neato_password

# Track the sun
sun:

# Telegram
telegram_bot:
  - platform: polling
    api_key: !secret telegram_api_key
    allowed_chat_ids:
      - !secret telegram_chat_ids
notify:
  - platform: telegram
    name: telegram
    chat_id: !secret telegram_chat_ids

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

# Pi-hole
pi_hole:

# Cloud
cloud:

group: !include groups.yaml
#automation: !include_dir_merge_list automation
automation: !include automations.yaml
script: !include scripts.yaml
sensor: !include_dir_merge_list sensor
#sensor: !include sensors.yaml

